"""Generates ``picker.html`` -- a standalone page for choosing subjects.

Everything is baked in at generation time: no fetches, no CDN, no fonts, no
build step. It therefore behaves identically opened from disk (``file://``) and
served from GitHub Pages, and the hourly workflow regenerates it so the subject
list can never drift from the live grid.

The page can commit your selection straight to GitHub, which is what makes the
calendar update without touching a terminal. That means holding a token, so:

* Content-Security-Policy pins the only reachable origin to ``api.github.com``
  and forbids every external script, style, font and image.
* The page is entirely self-contained -- nothing third-party can run in the
  origin that holds the token.
* The token is kept in memory only unless you explicitly ask otherwise, and the
  UI says plainly what it can do and how to revoke it.
* The edit is surgical: the ``include`` array is rewritten inside your original
  file text, so comments survive. The result is validated as JSON before it is
  ever sent, and a failed validation falls back to a clean re-serialisation.

Visual language follows mans.rtu.lv: pale mint ground, deep teal, mint pills,
16px radii, wide-tracked 12px labels.
"""

from __future__ import annotations

import json
from typing import Any, Dict

_PAGE = r"""<!-- Generated by rtusync. Edits here are overwritten on the next run. -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src https://api.github.com; img-src data:; form-action 'none'; base-uri 'none'">
<meta name="referrer" content="no-referrer">
<title>__TITLE__</title>
<style>
:root{
  --ground:#f4fbf9; --card:#ffffff; --ink:#0e1514; --muted:#4a6361;
  --brand:#005551; --brand-2:#006a65; --accent:#008765;
  --mint:#cce8e5; --mint-soft:#f2fffd; --line:#b9dedc; --line-soft:#e3f1ee;
  --danger:#8a3324; --radius:16px;
  --shadow:0 1px 2px rgba(0,85,81,.04), 0 8px 24px rgba(0,85,81,.06);
}
@media (prefers-color-scheme: dark){
  :root:not([data-theme="light"]){
    --ground:#0c1413; --card:#111d1b; --ink:#e8f4f1; --muted:#8fa8a4;
    --brand:#81d5ce; --brand-2:#66afa0; --accent:#81d5ce;
    --mint:#16302c; --mint-soft:#122422; --line:#23413d; --line-soft:#1a302d;
    --danger:#e8a08d;
    --shadow:0 1px 2px rgba(0,0,0,.3), 0 8px 24px rgba(0,0,0,.25);
  }
}
:root[data-theme="dark"]{
  --ground:#0c1413; --card:#111d1b; --ink:#e8f4f1; --muted:#8fa8a4;
  --brand:#81d5ce; --brand-2:#66afa0; --accent:#81d5ce;
  --mint:#16302c; --mint-soft:#122422; --line:#23413d; --line-soft:#1a302d;
  --danger:#e8a08d;
  --shadow:0 1px 2px rgba(0,0,0,.3), 0 8px 24px rgba(0,0,0,.25);
}
*{box-sizing:border-box}
body{
  margin:0; background:var(--ground); color:var(--ink);
  font-family:MarkPro,Geometria,Tahoma,Arial,system-ui,-apple-system,sans-serif;
  font-size:16px; line-height:1.5; -webkit-font-smoothing:antialiased;
}
.wrap{max-width:860px; margin:0 auto; padding:40px 20px 96px}
.eyebrow{font-size:12px; letter-spacing:.6px; text-transform:uppercase;
  color:var(--brand-2); margin:0 0 8px}
h1{font-size:30px; line-height:1.2; margin:0 0 10px; font-weight:500; color:var(--brand)}
.sub{margin:0; color:var(--muted); font-size:14px}
.sub b{color:var(--ink); font-weight:500}

.bar{
  position:sticky; top:0; z-index:20; margin:28px 0 20px;
  background:var(--card); border:1px solid var(--line); border-radius:var(--radius);
  box-shadow:var(--shadow); padding:14px 18px;
  display:flex; align-items:center; gap:16px; flex-wrap:wrap;
}
.tally{font-size:14px; color:var(--muted); flex:1 1 220px; min-width:0}
.tally b{color:var(--ink); font-weight:500}
.tally .drop{color:var(--brand-2)}
.dirty{
  display:inline-flex; align-items:center; gap:6px; margin-top:6px;
  font-size:12px; letter-spacing:.4px; padding:3px 10px; border-radius:999px;
  background:var(--mint); color:var(--brand); border:1px solid var(--line);
}
.dirty::before{content:"\25CF"; color:var(--accent); font-size:10px}
button.go.attention{box-shadow:0 0 0 3px rgba(0,135,101,.22)}
.btns{display:flex; gap:8px; flex-wrap:wrap}
button{
  font:inherit; font-size:12px; letter-spacing:.6px; cursor:pointer;
  background:var(--mint); color:var(--brand); border:1px solid transparent;
  border-radius:var(--radius); padding:9px 16px; transition:.15s;
}
button:hover:not(:disabled){background:var(--line)}
button:disabled{opacity:.45; cursor:not-allowed}
button.ghost{background:transparent; border-color:var(--line); color:var(--muted)}
button.ghost:hover:not(:disabled){background:var(--mint-soft); color:var(--brand)}
button.go{background:var(--brand); color:var(--ground); font-weight:500}
button.go:hover:not(:disabled){background:var(--brand-2)}
button:focus-visible{outline:2px solid var(--accent); outline-offset:2px}

.list{background:var(--card); border:1px solid var(--line); border-radius:var(--radius);
  box-shadow:var(--shadow); overflow:hidden}
.row{display:flex; align-items:flex-start; gap:14px; padding:16px 18px;
  border-top:1px solid var(--line-soft); cursor:pointer; transition:background .12s}
.row:first-child{border-top:0}
.row:hover{background:var(--mint-soft)}
.row.off{opacity:.5}
.row.pending{box-shadow:inset 3px 0 0 var(--accent)}
.row.pending .name::after{
  content:"\2022"; color:var(--accent); font-size:18px; line-height:0;
  position:relative; top:2px; margin-left:7px;
}
.row.off .name{text-decoration:line-through; text-decoration-color:var(--line)}
.box{flex:0 0 auto; width:20px; height:20px; margin-top:2px; border-radius:6px;
  border:1.5px solid var(--line); background:var(--card);
  display:grid; place-items:center; transition:.15s}
.row:not(.off) .box{background:var(--brand); border-color:var(--brand)}
.box svg{width:12px; height:12px; opacity:0; transition:opacity .15s}
.row:not(.off) .box svg{opacity:1}
input[type=checkbox]{position:absolute; opacity:0; width:0; height:0}
.meta{flex:1 1 auto; min-width:0}
.name{display:block; font-size:15px; font-weight:500; color:var(--ink); overflow-wrap:anywhere}
.en{display:block; font-size:13px; color:var(--muted); margin-top:2px; overflow-wrap:anywhere}
.chips{display:flex; gap:6px; flex-wrap:wrap; margin-top:8px}
.chip{font-size:11px; letter-spacing:.4px; padding:2px 8px; border-radius:999px;
  background:var(--mint-soft); color:var(--brand-2); border:1px solid var(--line-soft)}
.chip.code{font-variant-numeric:tabular-nums}
.count{display:block; flex:0 0 auto; text-align:right; min-width:78px;
  font-size:12px; color:var(--muted); font-variant-numeric:tabular-nums; line-height:1.35}
.count b{display:block; font-size:19px; color:var(--brand); font-weight:500; line-height:1.15}
.spark{display:flex; gap:2px; justify-content:flex-end; margin-top:6px; height:18px; align-items:flex-end}
.spark i{width:5px; background:var(--line); border-radius:1px; display:block}
.row:not(.off) .spark i{background:var(--brand-2)}

h2{font-size:12px; letter-spacing:.6px; text-transform:uppercase; color:var(--brand-2);
   margin:34px 0 10px; font-weight:500}
.panel{background:var(--card); border:1px solid var(--line); border-radius:var(--radius);
  box-shadow:var(--shadow); padding:18px}
pre{margin:0; padding:14px; background:var(--mint-soft); border:1px solid var(--line-soft);
  border-radius:10px; overflow-x:auto; font-size:12.5px; line-height:1.65;
  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; color:var(--ink)}
.note{font-size:13px; color:var(--muted); margin:14px 0 0}
.note code{background:var(--mint-soft); border:1px solid var(--line-soft); border-radius:5px;
  padding:1px 5px; font-size:12px; font-family:ui-monospace,Menlo,monospace}
.note b{color:var(--ink); font-weight:500}

.grid{display:grid; grid-template-columns:repeat(auto-fit,minmax(170px,1fr)); gap:12px}
label.f{display:block; font-size:11px; letter-spacing:.5px; text-transform:uppercase;
  color:var(--brand-2); margin-bottom:5px}
input[type=text],input[type=password]{
  width:100%; font:inherit; font-size:14px; padding:9px 12px; color:var(--ink);
  background:var(--mint-soft); border:1px solid var(--line); border-radius:10px;
}
input:focus{outline:2px solid var(--accent); outline-offset:1px}
.tokrow{margin-top:14px}
.chk{display:flex; align-items:center; gap:8px; margin-top:10px; font-size:13px; color:var(--muted)}
.chk input{width:16px; height:16px; position:static; opacity:1; accent-color:var(--brand)}
.warn{
  margin-top:14px; padding:12px 14px; border-radius:10px; font-size:12.5px; line-height:1.55;
  background:var(--mint-soft); border:1px solid var(--line); color:var(--muted);
}
.warn b{color:var(--ink); font-weight:500}
.warn code{font-family:ui-monospace,Menlo,monospace; font-size:11.5px}
.status{margin-top:14px; font-size:13px; min-height:20px}
.status.ok{color:var(--accent)} .status.bad{color:var(--danger)}
.actions{display:flex; gap:8px; align-items:center; margin-top:16px; flex-wrap:wrap}
.steps{margin:10px 0 0; padding-left:20px; font-size:13px; color:var(--muted)}
.steps li{margin:5px 0}
.foot{margin-top:30px; font-size:12px; color:var(--muted); text-align:center}
.toast{position:fixed; left:50%; bottom:26px; transform:translate(-50%,14px);
  background:var(--brand); color:var(--ground); padding:10px 20px; border-radius:999px;
  font-size:13px; opacity:0; pointer-events:none; transition:.22s; z-index:50; max-width:90vw}
.toast.on{opacity:1; transform:translate(-50%,0)}
@media (max-width:600px){
  .wrap{padding:26px 14px 80px} h1{font-size:23px}
  .count{min-width:56px} .spark{display:none}
}
</style>

<div class="wrap">
  <p class="eyebrow">__EYEBROW__</p>
  <h1>__HEADING__</h1>
  <p class="sub">__SUBTITLE__</p>

  <div class="bar">
    <div class="tally" id="tally"></div>
    <div class="btns">
      <button class="ghost" id="all">Visi</button>
      <button class="ghost" id="none">Neviens</button>
      <button class="ghost" id="reset">Atjaunot</button>
    </div>
  </div>

  <div class="list" id="list"></div>

  <h2>Publicēt uz GitHub</h2>
  <div class="panel">
    <div class="grid">
      <div><label class="f" for="owner">Lietotājs</label><input type="text" id="owner" spellcheck="false" autocapitalize="none" placeholder="jusu-lietotajvards"></div>
      <div><label class="f" for="repo">Repozitorijs</label><input type="text" id="repo" spellcheck="false" autocapitalize="none" placeholder="rtu-calendar"></div>
      <div><label class="f" for="branch">Zars</label><input type="text" id="branch" spellcheck="false" autocapitalize="none" placeholder="main"></div>
      <div><label class="f" for="path">Fails</label><input type="text" id="path" spellcheck="false" autocapitalize="none" placeholder="config.json"></div>
    </div>

    <div class="tokrow">
      <label class="f" for="token">Piekļuves pilnvara (fine-grained token)</label>
      <input type="password" id="token" autocomplete="off" spellcheck="false" placeholder="github_pat_...">
      <div class="chk">
        <input type="checkbox" id="remember">
        <label for="remember">Atcerēties šajā ierīcē (glabā pārlūkā)</label>
      </div>
    </div>

    <div class="warn">
      <b>Izveido fine-grained token</b> — github.com → Settings → Developer settings →
      Personal access tokens → Fine-grained tokens. Ierobežo to <b>tikai uz šo vienu
      repozitoriju</b> un dod vienīgi <code>Contents: Read and write</code>.
      Uzliec derīguma termiņu.<br><br>
      Pilnvara ļauj rakstīt šajā repozitorijā. Pēc noklusējuma tā netiek saglabāta —
      aizverot lapu, tā pazūd. Atsauc jebkurā laikā tajā pašā GitHub lapā.
    </div>

    <div class="actions">
      <button class="go" id="publish">Saglabāt un publicēt</button>
      <button class="ghost" id="copy">Kopēt include</button>
      <button class="ghost" id="dl">Lejupielādēt config.json</button>
      <button class="ghost" id="forget" hidden>Aizmirst pilnvaru</button>
    </div>
    <div class="status" id="status"></div>

    <p class="note">Pēc publicēšanas darbplūsma pārbūvē <code>planning.ics</code> dažu
    minūšu laikā. Kalendāra lietotne to ievilks pēc savas atsvaidzināšanas grafika.</p>
  </div>

  <h2>config.json → subjects.include</h2>
  <div class="panel">
    <pre id="out"></pre>
    <p class="note">Ja nelieto pilnvaru: <b>Kopēt include</b> saglabā komentārus,
    <b>Lejupielādēt</b> dod tīru failu. Abos gadījumos jāizdara <code>git commit</code>.</p>
  </div>

  <p class="foot">Ģenerēts __GENERATED__ · __EVENTS__ nodarbības · dati no nodarbibas.rtu.lv</p>
</div>
<div class="toast" id="toast"></div>

<script id="data" type="application/json">__DATA__</script>
<script>
(function(){
  var D = JSON.parse(document.getElementById('data').textContent);
  var SKEY = 'rtusync.picker.' + D.semesterProgramId;
  var TKEY = 'rtusync.token.' + D.semesterProgramId;
  var committed = D.subjects.filter(function(s){ return s.included; }).map(function(s){ return s.key; });

  function lsGet(k){ try { return localStorage.getItem(k); } catch(e){ return null; } }
  function lsSet(k,v){ try { localStorage.setItem(k,v); } catch(e){} }
  function lsDel(k){ try { localStorage.removeItem(k); } catch(e){} }

  var stored = null;
  try { stored = JSON.parse(lsGet(SKEY)); } catch(e) { stored = null; }
  var sel = new Set(Array.isArray(stored) ? stored : committed);

  /* ---------------------------------------------------------------- list */
  var maxMonth = 1;
  D.subjects.forEach(function(s){ s.months.forEach(function(m){ if (m > maxMonth) maxMonth = m; }); });
  var list = document.getElementById('list');

  D.subjects.forEach(function(s){
    var row = document.createElement('label');
    row.className = 'row';
    row.innerHTML =
      '<input type="checkbox">' +
      '<span class="box"><svg viewBox="0 0 12 12" fill="none" aria-hidden="true">' +
        '<path d="M2 6.2 4.6 8.8 10 3.4" stroke="#fff" stroke-width="2" ' +
        'stroke-linecap="round" stroke-linejoin="round"/></svg></span>' +
      '<span class="meta"><span class="name"></span><span class="en"></span>' +
      '<span class="chips"></span></span>' +
      '<span class="count"><b></b>nodarbības<span class="spark"></span></span>';
    row.querySelector('.name').textContent = s.key;
    row.querySelector('.en').textContent = s.titleEn || '';
    var chips = row.querySelector('.chips');
    if (s.code) {
      var c0 = document.createElement('span');
      c0.className = 'chip code'; c0.textContent = s.code; chips.appendChild(c0);
    }
    s.types.forEach(function(t){
      var c = document.createElement('span'); c.className = 'chip'; c.textContent = t; chips.appendChild(c);
    });
    row.querySelector('.count b').textContent = s.count;
    var spark = row.querySelector('.spark');
    s.months.forEach(function(m){
      var bar = document.createElement('i');
      bar.style.height = Math.max(2, Math.round(18 * m / maxMonth)) + 'px';
      spark.appendChild(bar);
    });
    var cb = row.querySelector('input');
    cb.checked = sel.has(s.key);
    cb.addEventListener('change', function(){
      if (cb.checked) sel.add(s.key); else sel.delete(s.key);
      lsSet(SKEY, JSON.stringify(Array.from(sel))); render();
    });
    row._cb = cb; row._key = s.key; row._count = s.count;
    list.appendChild(row);
  });

  function ordered(){
    return D.subjects.filter(function(s){ return sel.has(s.key); }).map(function(s){ return s.key; });
  }

  function render(){
    var kept = 0, dropped = 0;
    [].forEach.call(list.children, function(row){
      var on = sel.has(row._key);
      row.classList.toggle('off', !on);
      row._cb.checked = on;
      if (on) kept += row._count; else dropped += row._count;
    });
    // Local edits and published state must never look the same -- that is how
    // you end up with a subject you thought you had dropped still in the feed.
    var live = new Set(committed);
    var pending = 0;
    [].forEach.call(list.children, function(row){
      var differs = sel.has(row._key) !== live.has(row._key);
      row.classList.toggle('pending', differs);
      if (differs) pending++;
    });

    var html = '<b>' + sel.size + '</b> no ' + D.subjects.length + ' priekšmetiem · ' +
      '<b>' + kept + '</b> nodarbības kalendārā' +
      (dropped ? ' · <span class="drop">' + dropped + ' izlaistas</span>' : '');
    if (pending) {
      html += '<br><span class="dirty">' + pending +
        (pending === 1 ? ' nepublicēta izmaiņa' : ' nepublicētas izmaiņas') +
        ' — nospied “Saglabāt un publicēt”</span>';
    }
    document.getElementById('tally').innerHTML = html;

    var go = document.getElementById('publish');
    if (go) go.classList.toggle('attention', pending > 0);
    document.getElementById('out').textContent = includeBlock();
  }

  function includeBlock(){
    var picked = ordered();
    if (!picked.length) return '"include": []';
    return '"include": [\n' + picked.map(function(k, i){
      return '  ' + JSON.stringify(k) + (i < picked.length - 1 ? ',' : '');
    }).join('\n') + '\n]';
  }

  /* ------------------------------------------- config text, comments kept */
  // Same algorithm as rtusync/config.py: strip // # and /* */ outside strings.
  function stripComments(text){
    var out = '', i = 0, n = text.length, inStr = false, q = '';
    while (i < n){
      var ch = text[i];
      if (inStr){
        out += ch;
        if (ch === '\\' && i + 1 < n){ out += text[i+1]; i += 2; continue; }
        if (ch === q) inStr = false;
        i++; continue;
      }
      if (ch === '"' || ch === "'"){ inStr = true; q = ch; out += ch; i++; continue; }
      if (ch === '/' && text[i+1] === '/'){ while (i < n && text[i] !== '\n') i++; continue; }
      if (ch === '#'){ while (i < n && text[i] !== '\n') i++; continue; }
      if (ch === '/' && text[i+1] === '*'){
        var e = text.indexOf('*/', i + 2); i = e === -1 ? n : e + 2; continue;
      }
      out += ch; i++;
    }
    return out;
  }

  function cleanConfig(){
    var cfg = JSON.parse(JSON.stringify(D.config));
    cfg.subjects = cfg.subjects || {};
    cfg.subjects.include = ordered();
    return JSON.stringify(cfg, null, 2) + '\n';
  }

  // Rewrite the include array inside the ORIGINAL file text so comments survive.
  function configText(){
    var raw = D.rawConfig || '';
    var re = /([ \t]*)"include"[ \t]*:[ \t]*\[[\s\S]*?\]/;
    var m = raw.match(re);
    if (m){
      var indent = m[1] || '      ';
      var picked = ordered();
      var body = picked.length
        ? '[\n' + picked.map(function(k, i){
            return indent + '  ' + JSON.stringify(k) + (i < picked.length - 1 ? ',' : '');
          }).join('\n') + '\n' + indent + ']'
        : '[]';
      var candidate = raw.replace(re, indent + '"include": ' + body);
      try {
        var parsed = JSON.parse(stripComments(candidate));
        var got = (parsed.subjects || {}).include || [];
        if (got.length === picked.length && got.every(function(v, i){ return v === picked[i]; })) {
          return candidate;                       // verified before it is ever sent
        }
      } catch(e){ /* fall through */ }
    }
    return cleanConfig();                          // safe fallback
  }

  /* ------------------------------------------------------------- toast */
  var toast = document.getElementById('toast'), timer;
  function say(msg){
    toast.textContent = msg; toast.classList.add('on');
    clearTimeout(timer); timer = setTimeout(function(){ toast.classList.remove('on'); }, 2400);
  }
  function status(msg, cls){
    var el = document.getElementById('status');
    el.textContent = msg; el.className = 'status' + (cls ? ' ' + cls : '');
  }

  /* ------------------------------------------------------------ buttons */
  document.getElementById('all').onclick = function(){
    D.subjects.forEach(function(s){ sel.add(s.key); });
    lsSet(SKEY, JSON.stringify(Array.from(sel))); render();
  };
  document.getElementById('none').onclick = function(){
    sel.clear(); lsSet(SKEY, JSON.stringify([])); render();
  };
  document.getElementById('reset').onclick = function(){
    sel = new Set(committed); lsSet(SKEY, JSON.stringify(committed)); render();
    say('Atjaunots uz config.json');
  };
  document.getElementById('copy').onclick = function(){
    var text = includeBlock();
    function fallback(){
      var ta = document.createElement('textarea');
      ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0';
      document.body.appendChild(ta); ta.select();
      try { document.execCommand('copy'); say('Nokopēts'); } catch(e){ say('Nevarēja nokopēt'); }
      document.body.removeChild(ta);
    }
    if (navigator.clipboard && navigator.clipboard.writeText)
      navigator.clipboard.writeText(text).then(function(){ say('Nokopēts'); }, fallback);
    else fallback();
  };
  document.getElementById('dl').onclick = function(){
    var blob = new Blob([cleanConfig()], {type:'application/json'});
    var a = document.createElement('a');
    a.href = URL.createObjectURL(blob); a.download = 'config.json';
    document.body.appendChild(a); a.click();
    setTimeout(function(){ URL.revokeObjectURL(a.href); document.body.removeChild(a); }, 0);
    say('config.json lejupielādēts');
  };

  /* ------------------------------------------------------ github publish */
  var F = {
    owner: document.getElementById('owner'), repo: document.getElementById('repo'),
    branch: document.getElementById('branch'), path: document.getElementById('path'),
    token: document.getElementById('token'), remember: document.getElementById('remember'),
    forget: document.getElementById('forget'), publish: document.getElementById('publish')
  };
  var gh = D.github || {};
  F.owner.value  = lsGet(SKEY + '.owner')  || gh.owner  || '';
  F.repo.value   = lsGet(SKEY + '.repo')   || gh.repo   || '';
  F.branch.value = lsGet(SKEY + '.branch') || gh.branch || 'main';
  F.path.value   = lsGet(SKEY + '.path')   || gh.path   || 'config.json';
  ['owner','repo','branch','path'].forEach(function(k){
    F[k].addEventListener('change', function(){ lsSet(SKEY + '.' + k, F[k].value.trim()); });
  });

  var savedToken = lsGet(TKEY);
  if (savedToken){ F.token.value = savedToken; F.remember.checked = true; F.forget.hidden = false; }
  F.forget.onclick = function(){
    lsDel(TKEY); F.token.value = ''; F.remember.checked = false;
    F.forget.hidden = true; status('Pilnvara izdzēsta no šīs ierīces.', 'ok');
  };

  function b64(str){
    var bytes = new TextEncoder().encode(str), bin = '';
    for (var i = 0; i < bytes.length; i += 0x8000)
      bin += String.fromCharCode.apply(null, bytes.subarray(i, i + 0x8000));
    return btoa(bin);
  }

  function explain(code, body){
    if (code === 401) return 'Pilnvara nederīga vai beigusies (401).';
    if (code === 403) return 'Pilnvarai trūkst tiesību "Contents: Read and write" (403).';
    if (code === 404) return 'Repozitorijs, zars vai fails nav atrasts — vai pilnvarai nav piešķirts šis repozitorijs (404).';
    if (code === 409) return 'Fails mainījies vienlaikus (409). Pārlādē lapu un mēģini vēlreiz.';
    if (code === 422) return 'GitHub noraidīja pieprasījumu (422): ' + (body && body.message || '');
    return 'GitHub kļūda ' + code + ': ' + (body && body.message || '');
  }

  F.publish.onclick = async function(){
    var owner = F.owner.value.trim(), repo = F.repo.value.trim();
    var branch = F.branch.value.trim() || 'main', path = F.path.value.trim() || 'config.json';
    var token = F.token.value.trim();
    if (!owner || !repo){ status('Ievadi lietotāju un repozitoriju.', 'bad'); return; }
    if (!token){ status('Ievadi piekļuves pilnvaru.', 'bad'); return; }
    if (!sel.size && !confirm('Neviens priekšmets nav izvēlēts — kalendārs paliks tukšs. Turpināt?')) return;

    F.publish.disabled = true;
    status('Publicē…');
    var api = 'https://api.github.com/repos/' + encodeURIComponent(owner) + '/' +
              encodeURIComponent(repo) + '/contents/' +
              path.split('/').map(encodeURIComponent).join('/');
    var headers = {
      'Authorization': 'Bearer ' + token,
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28'
    };
    try {
      var sha = null;
      var get = await fetch(api + '?ref=' + encodeURIComponent(branch), {headers: headers});
      if (get.status === 200){ sha = (await get.json()).sha; }
      else if (get.status !== 404){
        status(explain(get.status, await get.json().catch(function(){ return null; })), 'bad');
        F.publish.disabled = false; return;
      }
      var payload = {
        message: 'picker: ' + sel.size + ' of ' + D.subjects.length + ' subjects',
        content: b64(configText()),
        branch: branch
      };
      if (sha) payload.sha = sha;
      var put = await fetch(api, {
        method: 'PUT',
        headers: Object.assign({'Content-Type': 'application/json'}, headers),
        body: JSON.stringify(payload)
      });
      var body = await put.json().catch(function(){ return null; });
      if (!put.ok){ status(explain(put.status, body), 'bad'); F.publish.disabled = false; return; }

      if (F.remember.checked){ lsSet(TKEY, token); F.forget.hidden = false; }
      else { lsDel(TKEY); F.forget.hidden = true; }
      committed = ordered();
      var short = body && body.commit && body.commit.sha ? body.commit.sha.slice(0, 7) : '';
      status('Publicēts' + (short ? ' (' + short + ')' : '') +
             '. Darbplūsma pārbūvēs kalendāru dažu minūšu laikā.', 'ok');
      say('Publicēts uz GitHub');
    } catch (e){
      status('Neizdevās savienoties ar GitHub: ' + e.message, 'bad');
    }
    F.publish.disabled = false;
  };

  render();
})();
</script>
"""


def render_picker(data: Dict[str, Any], cfg) -> str:
    total = sum(s["count"] for s in data["subjects"])
    heading = cfg.calendar_name or "RTU nodarbibas"
    bits = []
    if cfg.semester_label:
        bits.append("<b>%s</b>" % _esc(cfg.semester_label))
    if cfg.group_label:
        bits.append(_esc(cfg.group_label))
    bits.append("semesterProgramId %d" % cfg.semester_program_id)

    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    payload = payload.replace("</", "<\\/")      # never close our own <script>

    out = _PAGE
    for token, value in (
        ("__TITLE__", _esc("%s — priekšmetu izvēle" % heading)),
        ("__EYEBROW__", "Nodarbību izvēle"),
        ("__HEADING__", _esc(heading)),
        ("__SUBTITLE__", " · ".join(bits)),
        ("__GENERATED__", data["generated"]),
        ("__EVENTS__", str(total)),
        ("__DATA__", payload),
    ):
        out = out.replace(token, value)
    return out


def _esc(text: str) -> str:
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))
